### ISSUE TITLE
Change the layout of the landing page.

### ISSUE THREAD

**Issue by itsromack** [mdtsantos/Project-Claims#2]
Change the layout of the index page.

Every button should have a different color. Add some texture to the buttons.

Here's a nice read about CTAs
http://blog.hubspot.com/marketing/great-call-to-action-examples

**Comment by mdtsantos** [comment]
Hi sir! May mockup po ba tau for the page? Pra mapagbasehan ko ng code. thank you!

**Comment by itsromack** [comment]
please propose a design, as long as its working and intuitive
