### ISSUE TITLE
Landing Page Mock Up

### ISSUE THREAD

**Issue by mdtsantos** [mdtsantos/Project-Claims#8]
![home copy](https://cloud.githubusercontent.com/assets/6382101/12576952/57aa8b7e-c452-11e5-898f-ef4be26a772d.png)

**Comment by itsromack** [comment]
ok good, cge use that

**Comment by itsromack** [comment]
Menu

News | Assign a Claim | Contact Us | About Us | Privacy Policy

CTA for "Assign a Claim" button.

Regarding the color theme, can you please create a version for this shades https://color.adobe.com/create/color-wheel/?base=2&rule=Shades&selected=3&name=My%20Color%20Theme&mode=rgb&rgbvalues=0.5363788269237134,0.10458480595427713,0.75,0.3575858846158089,0.06972320396951809,0.5,0.7151717692316178,0.13944640793903618,1,0.17879294230790446,0.034861601984759044,0.25,0.6436545923084561,0.12550176714513256,0.9&swatchOrder=0,1,2,3,4

**Comment by mdtsantos** [comment]
noted po.ty

**Comment by mdtsantos** [comment]
![revisedhome1](https://cloud.githubusercontent.com/assets/6382101/12673459/db34f35a-c6b7-11e5-9abd-d1e30c1cef0b.png)

**Comment by itsromack** [comment]
nice :)

**Comment by mdtsantos** [comment]
Done the front end sir.

**Comment by itsromack** [comment]
ok good. learn how to create a git branch. and use it to work on your other tasks, para hindi sa master branch ka nagko-commit palagi
